inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false
